{
    'name': 'CloudFone Sale',
    'category': 'cf',
    'author': 'uviah',
    'description': 'Sale customize',
    'depends': [
        'base',
        'sale',
        'cf_product',
        'cf_security',
        'cf_customer',
        'purchase',
        'report_py3o',
        'cf_convert_money',
        'helpdesk',
        'sale_stock',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/cf_update_functions_data.xml',
        'data/register_data.xml',
        'data/sale_order_source_data.xml',
        'wizards/service_addon_order_lines_wizard.xml',
        'wizards/search_order_wizard.xml',
        'views/sale_order.xml',
        'views/sale_service.xml',
        'views/res_partner.xml',
        'views/purchase_config_view.xml',
        'views/purchase_order.xml',
        'views/account_invoice.xml',
        'views/crm_team.xml',
        'views/helpdesk.xml',
        'views/capacity_price.xml',
        'views/external_config.xml',
        'views/import_capacity_price.xml',
        'views/web_asset.xml',
        'reports/report.xml',
        'reports/sale_order_info_template.xml',
        'reports/sale_report.xml',
    ],
    'installable': True,
}