from . import sale_order
from . import sale_order_line
from . import sale_service
from . import purchase_order
from . import purchase_order_line
from . import purchase_config_settings
from . import account_invoice_line
from . import external_config
from . import account_invoice
from . import crm_team
from . import res_partner
from . import helpdesk
from . import stock_picking
from . import capacity_price
from . import import_capacity_price